# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {} is {} kilometer'.format(planet,diameter))

The diameter of Earth is 12742 kilometer


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print('Array of 10 Zeros',array)


Array of 10 Zeros [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print('Array of 10 fives',array)

Array of 10 fives [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,35,2)
print('Array of all even nos from 20 to 35',array)

Array of all even nos from 20 to 35 [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x=array(a,b)

AttributeError: ignored

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
lst=[[1,'Amish',20],[2,'Priyanka',20],[3,'Swathi',20]]
df=pd.DataFrame(lst,columns=['S.No','name','age'])
print(df)

   S.No      name  age
0     1     Amish   20
1     2  Priyanka   20
2     3    Swathi   20


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime

test_date=datetime.datetime.strptime("01-1-2023", "%d-%m-%y")

k=41

date_generated=pd.date_range(test_date,periods=k)
print(date_generated.strftime("%d-%m-%y"))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lst=[[1, 'aaa', 22], [2, 'bbb', 25]]
df=pd.DataFrame(lst,columns=['S.No','name','age'])
print(df)

   S.No name  age
0     1  aaa   22
1     2  bbb   25
